FROM ubuntu:18.04
RUN apt update -y &&\
    apt install -y python3-pip &&\
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# copy project
COPY . /usr/src/app/